// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/device.proto

/*
Package device is a generated protocol buffer package.

It is generated from these files:
	messages/device.proto

It has these top-level messages:
	Box
	Device
	Item
	Property
	PropertyUpdate
	StateUpdate
	UpdateReq
	UpdateRes
	Update
*/
package device

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import basetypes "github.com/roderm/audio-panel-protobuf/go/msg/basetypes"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Box struct {
}

func (m *Box) Reset()                    { *m = Box{} }
func (m *Box) String() string            { return proto.CompactTextString(m) }
func (*Box) ProtoMessage()               {}
func (*Box) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Device struct {
	Identifier string  `protobuf:"bytes,1,opt,name=Identifier" json:"Identifier"`
	Name       string  `protobuf:"bytes,2,opt,name=Name" json:"Name"`
	Items      []*Item `protobuf:"bytes,10,rep,name=Items" json:"Items"`
}

func (m *Device) Reset()                    { *m = Device{} }
func (m *Device) String() string            { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()               {}
func (*Device) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Device) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *Device) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Device) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type Item struct {
	Identifier string      `protobuf:"bytes,1,opt,name=Identifier" json:"Identifier"`
	Name       string      `protobuf:"bytes,2,opt,name=Name" json:"Name"`
	Type       string      `protobuf:"bytes,3,opt,name=Type" json:"Type"`
	Properties []*Property `protobuf:"bytes,10,rep,name=Properties" json:"Properties"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Item) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Item) GetProperties() []*Property {
	if m != nil {
		return m.Properties
	}
	return nil
}

type Property struct {
	Name string `protobuf:"bytes,1,opt,name=Name" json:"Name"`
	// Types that are valid to be assigned to Value:
	//	*Property_Boolean
	//	*Property_Number
	//	*Property_Decimal
	//	*Property_Text
	//	*Property_List
	Value isProperty_Value `protobuf_oneof:"Value"`
}

func (m *Property) Reset()                    { *m = Property{} }
func (m *Property) String() string            { return proto.CompactTextString(m) }
func (*Property) ProtoMessage()               {}
func (*Property) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type isProperty_Value interface {
	isProperty_Value()
}

type Property_Boolean struct {
	Boolean bool `protobuf:"varint,2,opt,name=Boolean,oneof"`
}
type Property_Number struct {
	Number int64 `protobuf:"varint,3,opt,name=Number,oneof"`
}
type Property_Decimal struct {
	Decimal float32 `protobuf:"fixed32,4,opt,name=Decimal,oneof"`
}
type Property_Text struct {
	Text string `protobuf:"bytes,5,opt,name=Text,oneof"`
}
type Property_List struct {
	List *basetypes.ValueList `protobuf:"bytes,6,opt,name=List,oneof"`
}

func (*Property_Boolean) isProperty_Value() {}
func (*Property_Number) isProperty_Value()  {}
func (*Property_Decimal) isProperty_Value() {}
func (*Property_Text) isProperty_Value()    {}
func (*Property_List) isProperty_Value()    {}

func (m *Property) GetValue() isProperty_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Property) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Property) GetBoolean() bool {
	if x, ok := m.GetValue().(*Property_Boolean); ok {
		return x.Boolean
	}
	return false
}

func (m *Property) GetNumber() int64 {
	if x, ok := m.GetValue().(*Property_Number); ok {
		return x.Number
	}
	return 0
}

func (m *Property) GetDecimal() float32 {
	if x, ok := m.GetValue().(*Property_Decimal); ok {
		return x.Decimal
	}
	return 0
}

func (m *Property) GetText() string {
	if x, ok := m.GetValue().(*Property_Text); ok {
		return x.Text
	}
	return ""
}

func (m *Property) GetList() *basetypes.ValueList {
	if x, ok := m.GetValue().(*Property_List); ok {
		return x.List
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Property) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Property_OneofMarshaler, _Property_OneofUnmarshaler, _Property_OneofSizer, []interface{}{
		(*Property_Boolean)(nil),
		(*Property_Number)(nil),
		(*Property_Decimal)(nil),
		(*Property_Text)(nil),
		(*Property_List)(nil),
	}
}

func _Property_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Property)
	// Value
	switch x := m.Value.(type) {
	case *Property_Boolean:
		t := uint64(0)
		if x.Boolean {
			t = 1
		}
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *Property_Number:
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Number))
	case *Property_Decimal:
		b.EncodeVarint(4<<3 | proto.WireFixed32)
		b.EncodeFixed32(uint64(math.Float32bits(x.Decimal)))
	case *Property_Text:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Text)
	case *Property_List:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.List); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Property.Value has unexpected type %T", x)
	}
	return nil
}

func _Property_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Property)
	switch tag {
	case 2: // Value.Boolean
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Property_Boolean{x != 0}
		return true, err
	case 3: // Value.Number
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Property_Number{int64(x)}
		return true, err
	case 4: // Value.Decimal
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.Value = &Property_Decimal{math.Float32frombits(uint32(x))}
		return true, err
	case 5: // Value.Text
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &Property_Text{x}
		return true, err
	case 6: // Value.List
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(basetypes.ValueList)
		err := b.DecodeMessage(msg)
		m.Value = &Property_List{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Property_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Property)
	// Value
	switch x := m.Value.(type) {
	case *Property_Boolean:
		n += proto.SizeVarint(2<<3 | proto.WireVarint)
		n += 1
	case *Property_Number:
		n += proto.SizeVarint(3<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.Number))
	case *Property_Decimal:
		n += proto.SizeVarint(4<<3 | proto.WireFixed32)
		n += 4
	case *Property_Text:
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Text)))
		n += len(x.Text)
	case *Property_List:
		s := proto.Size(x.List)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type PropertyUpdate struct {
	BoxIdentifier    string    `protobuf:"bytes,1,opt,name=BoxIdentifier" json:"BoxIdentifier"`
	DeviceIdentifier string    `protobuf:"bytes,2,opt,name=DeviceIdentifier" json:"DeviceIdentifier"`
	ItemIdentifier   string    `protobuf:"bytes,3,opt,name=ItemIdentifier" json:"ItemIdentifier"`
	State            *Property `protobuf:"bytes,4,opt,name=State" json:"State"`
}

func (m *PropertyUpdate) Reset()                    { *m = PropertyUpdate{} }
func (m *PropertyUpdate) String() string            { return proto.CompactTextString(m) }
func (*PropertyUpdate) ProtoMessage()               {}
func (*PropertyUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PropertyUpdate) GetBoxIdentifier() string {
	if m != nil {
		return m.BoxIdentifier
	}
	return ""
}

func (m *PropertyUpdate) GetDeviceIdentifier() string {
	if m != nil {
		return m.DeviceIdentifier
	}
	return ""
}

func (m *PropertyUpdate) GetItemIdentifier() string {
	if m != nil {
		return m.ItemIdentifier
	}
	return ""
}

func (m *PropertyUpdate) GetState() *Property {
	if m != nil {
		return m.State
	}
	return nil
}

type StateUpdate struct {
	Prop *PropertyUpdate `protobuf:"bytes,1,opt,name=Prop" json:"Prop"`
}

func (m *StateUpdate) Reset()                    { *m = StateUpdate{} }
func (m *StateUpdate) String() string            { return proto.CompactTextString(m) }
func (*StateUpdate) ProtoMessage()               {}
func (*StateUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *StateUpdate) GetProp() *PropertyUpdate {
	if m != nil {
		return m.Prop
	}
	return nil
}

type UpdateReq struct {
}

func (m *UpdateReq) Reset()                    { *m = UpdateReq{} }
func (m *UpdateReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateReq) ProtoMessage()               {}
func (*UpdateReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type UpdateRes struct {
}

func (m *UpdateRes) Reset()                    { *m = UpdateRes{} }
func (m *UpdateRes) String() string            { return proto.CompactTextString(m) }
func (*UpdateRes) ProtoMessage()               {}
func (*UpdateRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type Update struct {
}

func (m *Update) Reset()                    { *m = Update{} }
func (m *Update) String() string            { return proto.CompactTextString(m) }
func (*Update) ProtoMessage()               {}
func (*Update) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func init() {
	proto.RegisterType((*Box)(nil), "Box")
	proto.RegisterType((*Device)(nil), "Device")
	proto.RegisterType((*Item)(nil), "Item")
	proto.RegisterType((*Property)(nil), "Property")
	proto.RegisterType((*PropertyUpdate)(nil), "PropertyUpdate")
	proto.RegisterType((*StateUpdate)(nil), "StateUpdate")
	proto.RegisterType((*UpdateReq)(nil), "UpdateReq")
	proto.RegisterType((*UpdateRes)(nil), "UpdateRes")
	proto.RegisterType((*Update)(nil), "Update")
}

func init() { proto.RegisterFile("messages/device.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x92, 0xdd, 0x8a, 0xd4, 0x30,
	0x14, 0xc7, 0xa7, 0x3b, 0x6d, 0x77, 0xe6, 0x14, 0x57, 0x09, 0x0a, 0x61, 0x05, 0x2d, 0x51, 0x64,
	0x14, 0xb6, 0x85, 0x51, 0x7c, 0x80, 0xb2, 0x17, 0xb3, 0x20, 0x8b, 0xd4, 0x55, 0xd0, 0xbb, 0x74,
	0x7a, 0x76, 0x0c, 0x4c, 0x26, 0xb5, 0x49, 0x65, 0xe6, 0x99, 0xbc, 0xf2, 0x0d, 0x25, 0x49, 0xbb,
	0x74, 0xdc, 0xbb, 0xbd, 0xca, 0xf9, 0xff, 0xce, 0x67, 0x4e, 0x02, 0xcf, 0x24, 0x6a, 0xcd, 0x37,
	0xa8, 0xf3, 0x1a, 0x7f, 0x8b, 0x35, 0x66, 0x4d, 0xab, 0x8c, 0x3a, 0xa7, 0x77, 0xb8, 0xe2, 0x1a,
	0xcd, 0xa1, 0x41, 0xed, 0x3d, 0x2c, 0x82, 0x69, 0xa1, 0xf6, 0xec, 0x3b, 0xc4, 0x97, 0x2e, 0x81,
	0xbc, 0x00, 0xb8, 0xaa, 0x71, 0x67, 0xc4, 0xad, 0xc0, 0x96, 0x06, 0x69, 0xb0, 0x98, 0x97, 0x23,
	0x42, 0x08, 0x84, 0xd7, 0x5c, 0x22, 0x3d, 0x71, 0x1e, 0x67, 0x93, 0xe7, 0x10, 0x5d, 0x19, 0x94,
	0x9a, 0x42, 0x3a, 0x5d, 0x24, 0xcb, 0x28, 0xb3, 0xaa, 0xf4, 0x8c, 0x1d, 0x20, 0xb4, 0xc6, 0x83,
	0x0a, 0x13, 0x08, 0x6f, 0x0e, 0x0d, 0xd2, 0xa9, 0x67, 0xd6, 0x26, 0x6f, 0x01, 0x3e, 0xb7, 0xaa,
	0xc1, 0xd6, 0x08, 0x1c, 0x3a, 0xce, 0xb3, 0x1e, 0x1d, 0xca, 0x91, 0x93, 0xfd, 0x0d, 0x60, 0x36,
	0x38, 0xee, 0xea, 0x07, 0xa3, 0xfa, 0xe7, 0x70, 0x5a, 0x28, 0xb5, 0x45, 0xbe, 0x73, 0x6d, 0x67,
	0xab, 0x49, 0x39, 0x00, 0x42, 0x21, 0xbe, 0xee, 0x64, 0x85, 0xad, 0xeb, 0x3e, 0x5d, 0x4d, 0xca,
	0x5e, 0xdb, 0xac, 0x4b, 0x5c, 0x0b, 0xc9, 0xb7, 0x34, 0x4c, 0x83, 0xc5, 0x89, 0xcd, 0xea, 0x01,
	0x79, 0x0a, 0xe1, 0x0d, 0xee, 0x0d, 0x8d, 0x6c, 0x97, 0xd5, 0xa4, 0x74, 0x8a, 0xa4, 0x10, 0x7e,
	0x12, 0xda, 0xd0, 0x38, 0x0d, 0x16, 0xc9, 0x12, 0xb2, 0x6f, 0x7c, 0xdb, 0xa1, 0x25, 0x36, 0xc2,
	0x9e, 0xc5, 0x29, 0x44, 0x0e, 0xb2, 0x3f, 0x01, 0x9c, 0x0d, 0x33, 0x7f, 0x6d, 0x6a, 0x6e, 0x90,
	0xbc, 0x86, 0x47, 0x85, 0xda, 0xdf, 0x5b, 0xde, 0x31, 0x24, 0xef, 0xe0, 0x89, 0x7f, 0xc2, 0x51,
	0xa0, 0xdf, 0xe5, 0x3d, 0x4e, 0xde, 0xc0, 0x99, 0x7d, 0x93, 0x51, 0xa4, 0xdf, 0xf0, 0x7f, 0x94,
	0xbc, 0x84, 0xe8, 0x8b, 0xe1, 0x06, 0xdd, 0x3d, 0x8f, 0xd6, 0xec, 0x39, 0x5b, 0x42, 0xe2, 0x8c,
	0x7e, 0xd2, 0x57, 0x10, 0xda, 0x08, 0x37, 0x60, 0xb2, 0x7c, 0x9c, 0x1d, 0x5f, 0xa4, 0x74, 0x4e,
	0x96, 0xc0, 0xbc, 0xd7, 0xf8, 0x6b, 0x2c, 0x34, 0x9b, 0x41, 0xec, 0x45, 0xf1, 0xf1, 0xc7, 0x87,
	0x8d, 0x30, 0x3f, 0xbb, 0x2a, 0x5b, 0x2b, 0x99, 0xb7, 0xaa, 0xc6, 0x56, 0xe6, 0xbc, 0xab, 0x85,
	0xba, 0x68, 0xf8, 0x0e, 0xb7, 0x17, 0xee, 0xf7, 0x56, 0xdd, 0x6d, 0xbe, 0x51, 0xb9, 0xd4, 0x9b,
	0xfe, 0xbb, 0x57, 0xb1, 0xe3, 0xef, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x31, 0xce, 0x8c,
	0x08, 0x03, 0x00, 0x00,
}
