// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/device.proto

package msg // import "github.com/roderm/audio-panel-protobuf/go/msg"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import messages "messages"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Box struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Box) Reset()         { *m = Box{} }
func (m *Box) String() string { return proto.CompactTextString(m) }
func (*Box) ProtoMessage()    {}
func (*Box) Descriptor() ([]byte, []int) {
	return fileDescriptor_device_af39b4e6d68b4feb, []int{0}
}
func (m *Box) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Box.Unmarshal(m, b)
}
func (m *Box) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Box.Marshal(b, m, deterministic)
}
func (dst *Box) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Box.Merge(dst, src)
}
func (m *Box) XXX_Size() int {
	return xxx_messageInfo_Box.Size(m)
}
func (m *Box) XXX_DiscardUnknown() {
	xxx_messageInfo_Box.DiscardUnknown(m)
}

var xxx_messageInfo_Box proto.InternalMessageInfo

type Device struct {
	Identifier           string   `protobuf:"bytes,1,opt,name=Identifier" json:"Identifier"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name" json:"Name"`
	Items                []*Item  `protobuf:"bytes,10,rep,name=Items" json:"Items"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_device_af39b4e6d68b4feb, []int{1}
}
func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (dst *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(dst, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *Device) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Device) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type Item struct {
	Identifier           string      `protobuf:"bytes,1,opt,name=Identifier" json:"Identifier"`
	Name                 string      `protobuf:"bytes,2,opt,name=Name" json:"Name"`
	Type                 string      `protobuf:"bytes,3,opt,name=Type" json:"Type"`
	Properties           []*Property `protobuf:"bytes,10,rep,name=Properties" json:"Properties"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_device_af39b4e6d68b4feb, []int{2}
}
func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (dst *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(dst, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Item) GetProperties() []*Property {
	if m != nil {
		return m.Properties
	}
	return nil
}

type Property struct {
	Name string `protobuf:"bytes,1,opt,name=Name" json:"Name"`
	// Types that are valid to be assigned to Value:
	//	*Property_Boolean
	//	*Property_Number
	//	*Property_Decimal
	//	*Property_Text
	//	*Property_List
	Value                isProperty_Value `protobuf_oneof:"Value"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Property) Reset()         { *m = Property{} }
func (m *Property) String() string { return proto.CompactTextString(m) }
func (*Property) ProtoMessage()    {}
func (*Property) Descriptor() ([]byte, []int) {
	return fileDescriptor_device_af39b4e6d68b4feb, []int{3}
}
func (m *Property) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Property.Unmarshal(m, b)
}
func (m *Property) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Property.Marshal(b, m, deterministic)
}
func (dst *Property) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Property.Merge(dst, src)
}
func (m *Property) XXX_Size() int {
	return xxx_messageInfo_Property.Size(m)
}
func (m *Property) XXX_DiscardUnknown() {
	xxx_messageInfo_Property.DiscardUnknown(m)
}

var xxx_messageInfo_Property proto.InternalMessageInfo

type isProperty_Value interface {
	isProperty_Value()
}

type Property_Boolean struct {
	Boolean bool `protobuf:"varint,2,opt,name=Boolean,oneof"`
}
type Property_Number struct {
	Number int64 `protobuf:"varint,3,opt,name=Number,oneof"`
}
type Property_Decimal struct {
	Decimal float32 `protobuf:"fixed32,4,opt,name=Decimal,oneof"`
}
type Property_Text struct {
	Text string `protobuf:"bytes,5,opt,name=Text,oneof"`
}
type Property_List struct {
	List *messages.ValueList `protobuf:"bytes,6,opt,name=List,oneof"`
}

func (*Property_Boolean) isProperty_Value() {}
func (*Property_Number) isProperty_Value()  {}
func (*Property_Decimal) isProperty_Value() {}
func (*Property_Text) isProperty_Value()    {}
func (*Property_List) isProperty_Value()    {}

func (m *Property) GetValue() isProperty_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Property) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Property) GetBoolean() bool {
	if x, ok := m.GetValue().(*Property_Boolean); ok {
		return x.Boolean
	}
	return false
}

func (m *Property) GetNumber() int64 {
	if x, ok := m.GetValue().(*Property_Number); ok {
		return x.Number
	}
	return 0
}

func (m *Property) GetDecimal() float32 {
	if x, ok := m.GetValue().(*Property_Decimal); ok {
		return x.Decimal
	}
	return 0
}

func (m *Property) GetText() string {
	if x, ok := m.GetValue().(*Property_Text); ok {
		return x.Text
	}
	return ""
}

func (m *Property) GetList() *messages.ValueList {
	if x, ok := m.GetValue().(*Property_List); ok {
		return x.List
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Property) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Property_OneofMarshaler, _Property_OneofUnmarshaler, _Property_OneofSizer, []interface{}{
		(*Property_Boolean)(nil),
		(*Property_Number)(nil),
		(*Property_Decimal)(nil),
		(*Property_Text)(nil),
		(*Property_List)(nil),
	}
}

func _Property_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Property)
	// Value
	switch x := m.Value.(type) {
	case *Property_Boolean:
		t := uint64(0)
		if x.Boolean {
			t = 1
		}
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *Property_Number:
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Number))
	case *Property_Decimal:
		b.EncodeVarint(4<<3 | proto.WireFixed32)
		b.EncodeFixed32(uint64(math.Float32bits(x.Decimal)))
	case *Property_Text:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Text)
	case *Property_List:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.List); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Property.Value has unexpected type %T", x)
	}
	return nil
}

func _Property_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Property)
	switch tag {
	case 2: // Value.Boolean
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Property_Boolean{x != 0}
		return true, err
	case 3: // Value.Number
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Property_Number{int64(x)}
		return true, err
	case 4: // Value.Decimal
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.Value = &Property_Decimal{math.Float32frombits(uint32(x))}
		return true, err
	case 5: // Value.Text
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &Property_Text{x}
		return true, err
	case 6: // Value.List
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(messages.ValueList)
		err := b.DecodeMessage(msg)
		m.Value = &Property_List{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Property_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Property)
	// Value
	switch x := m.Value.(type) {
	case *Property_Boolean:
		n += 1 // tag and wire
		n += 1
	case *Property_Number:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Number))
	case *Property_Decimal:
		n += 1 // tag and wire
		n += 4
	case *Property_Text:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Text)))
		n += len(x.Text)
	case *Property_List:
		s := proto.Size(x.List)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type PropertyUpdate struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PropertyUpdate) Reset()         { *m = PropertyUpdate{} }
func (m *PropertyUpdate) String() string { return proto.CompactTextString(m) }
func (*PropertyUpdate) ProtoMessage()    {}
func (*PropertyUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_device_af39b4e6d68b4feb, []int{4}
}
func (m *PropertyUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropertyUpdate.Unmarshal(m, b)
}
func (m *PropertyUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropertyUpdate.Marshal(b, m, deterministic)
}
func (dst *PropertyUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropertyUpdate.Merge(dst, src)
}
func (m *PropertyUpdate) XXX_Size() int {
	return xxx_messageInfo_PropertyUpdate.Size(m)
}
func (m *PropertyUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_PropertyUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_PropertyUpdate proto.InternalMessageInfo

type StateUpdate struct {
	Prop                 *PropertyUpdate `protobuf:"bytes,1,opt,name=Prop" json:"Prop"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StateUpdate) Reset()         { *m = StateUpdate{} }
func (m *StateUpdate) String() string { return proto.CompactTextString(m) }
func (*StateUpdate) ProtoMessage()    {}
func (*StateUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_device_af39b4e6d68b4feb, []int{5}
}
func (m *StateUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateUpdate.Unmarshal(m, b)
}
func (m *StateUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateUpdate.Marshal(b, m, deterministic)
}
func (dst *StateUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateUpdate.Merge(dst, src)
}
func (m *StateUpdate) XXX_Size() int {
	return xxx_messageInfo_StateUpdate.Size(m)
}
func (m *StateUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_StateUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_StateUpdate proto.InternalMessageInfo

func (m *StateUpdate) GetProp() *PropertyUpdate {
	if m != nil {
		return m.Prop
	}
	return nil
}

type UpdateReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateReq) Reset()         { *m = UpdateReq{} }
func (m *UpdateReq) String() string { return proto.CompactTextString(m) }
func (*UpdateReq) ProtoMessage()    {}
func (*UpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_device_af39b4e6d68b4feb, []int{6}
}
func (m *UpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReq.Unmarshal(m, b)
}
func (m *UpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReq.Marshal(b, m, deterministic)
}
func (dst *UpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReq.Merge(dst, src)
}
func (m *UpdateReq) XXX_Size() int {
	return xxx_messageInfo_UpdateReq.Size(m)
}
func (m *UpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReq proto.InternalMessageInfo

type UpdateRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRes) Reset()         { *m = UpdateRes{} }
func (m *UpdateRes) String() string { return proto.CompactTextString(m) }
func (*UpdateRes) ProtoMessage()    {}
func (*UpdateRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_device_af39b4e6d68b4feb, []int{7}
}
func (m *UpdateRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRes.Unmarshal(m, b)
}
func (m *UpdateRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRes.Marshal(b, m, deterministic)
}
func (dst *UpdateRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRes.Merge(dst, src)
}
func (m *UpdateRes) XXX_Size() int {
	return xxx_messageInfo_UpdateRes.Size(m)
}
func (m *UpdateRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRes proto.InternalMessageInfo

type Update struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Update) Reset()         { *m = Update{} }
func (m *Update) String() string { return proto.CompactTextString(m) }
func (*Update) ProtoMessage()    {}
func (*Update) Descriptor() ([]byte, []int) {
	return fileDescriptor_device_af39b4e6d68b4feb, []int{8}
}
func (m *Update) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Update.Unmarshal(m, b)
}
func (m *Update) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Update.Marshal(b, m, deterministic)
}
func (dst *Update) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Update.Merge(dst, src)
}
func (m *Update) XXX_Size() int {
	return xxx_messageInfo_Update.Size(m)
}
func (m *Update) XXX_DiscardUnknown() {
	xxx_messageInfo_Update.DiscardUnknown(m)
}

var xxx_messageInfo_Update proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Box)(nil), "Box")
	proto.RegisterType((*Device)(nil), "Device")
	proto.RegisterType((*Item)(nil), "Item")
	proto.RegisterType((*Property)(nil), "Property")
	proto.RegisterType((*PropertyUpdate)(nil), "PropertyUpdate")
	proto.RegisterType((*StateUpdate)(nil), "StateUpdate")
	proto.RegisterType((*UpdateReq)(nil), "UpdateReq")
	proto.RegisterType((*UpdateRes)(nil), "UpdateRes")
	proto.RegisterType((*Update)(nil), "Update")
}

func init() { proto.RegisterFile("messages/device.proto", fileDescriptor_device_af39b4e6d68b4feb) }

var fileDescriptor_device_af39b4e6d68b4feb = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xdf, 0x8a, 0xd4, 0x30,
	0x14, 0xc6, 0xa7, 0xdb, 0x3f, 0x3b, 0x73, 0x0a, 0x2a, 0x41, 0x21, 0xac, 0x20, 0x25, 0xde, 0xd4,
	0x8b, 0x69, 0xa1, 0xbe, 0x41, 0xd9, 0x8b, 0x59, 0x90, 0x45, 0xea, 0x2a, 0xe8, 0x5d, 0x3a, 0x3d,
	0x5b, 0x03, 0xcd, 0xa4, 0x36, 0xa9, 0x6c, 0x1f, 0xcb, 0x37, 0x94, 0xa4, 0xed, 0x52, 0x6f, 0xbd,
	0xca, 0xf9, 0x7e, 0xdf, 0x39, 0xe7, 0x4b, 0x20, 0xf0, 0x46, 0xa2, 0xd6, 0xbc, 0x45, 0x9d, 0x37,
	0xf8, 0x5b, 0x9c, 0x31, 0xeb, 0x07, 0x65, 0xd4, 0x0d, 0x7d, 0xc6, 0x35, 0xd7, 0x68, 0xa6, 0x1e,
	0xf5, 0xec, 0xb0, 0x10, 0xfc, 0x52, 0x3d, 0xb1, 0xef, 0x10, 0xdd, 0xba, 0x01, 0xf2, 0x0e, 0xe0,
	0xae, 0xc1, 0x8b, 0x11, 0x8f, 0x02, 0x07, 0xea, 0x25, 0x5e, 0x7a, 0xa8, 0x36, 0x84, 0x10, 0x08,
	0xee, 0xb9, 0x44, 0x7a, 0xe5, 0x1c, 0x57, 0x93, 0xb7, 0x10, 0xde, 0x19, 0x94, 0x9a, 0x42, 0xe2,
	0xa7, 0x71, 0x11, 0x66, 0x56, 0x55, 0x33, 0x63, 0x13, 0x04, 0xb6, 0xf8, 0xaf, 0xc5, 0x04, 0x82,
	0x87, 0xa9, 0x47, 0xea, 0xcf, 0xcc, 0xd6, 0xe4, 0x03, 0xc0, 0xe7, 0x41, 0xf5, 0x38, 0x18, 0x81,
	0x6b, 0xe2, 0x21, 0x5b, 0xd0, 0x54, 0x6d, 0x4c, 0xf6, 0xc7, 0x83, 0xfd, 0x6a, 0x3c, 0xef, 0xf7,
	0x36, 0xfb, 0x6f, 0xe0, 0xba, 0x54, 0xaa, 0x43, 0x7e, 0x71, 0xb1, 0xfb, 0xd3, 0xae, 0x5a, 0x01,
	0xa1, 0x10, 0xdd, 0x8f, 0xb2, 0xc6, 0xc1, 0xa5, 0xfb, 0xa7, 0x5d, 0xb5, 0x68, 0x3b, 0x75, 0x8b,
	0x67, 0x21, 0x79, 0x47, 0x83, 0xc4, 0x4b, 0xaf, 0xec, 0xd4, 0x02, 0xc8, 0x6b, 0x08, 0x1e, 0xf0,
	0xc9, 0xd0, 0xd0, 0xa6, 0x9c, 0x76, 0x95, 0x53, 0x24, 0x81, 0xe0, 0x93, 0xd0, 0x86, 0x46, 0x89,
	0x97, 0xc6, 0x05, 0x64, 0xdf, 0x78, 0x37, 0xa2, 0x25, 0xb6, 0xc3, 0x9e, 0xe5, 0x35, 0x84, 0x0e,
	0xb2, 0x57, 0xf0, 0x62, 0xbd, 0xf2, 0xd7, 0xbe, 0xe1, 0x06, 0x59, 0x01, 0xf1, 0x17, 0xc3, 0x0d,
	0xce, 0x92, 0xbc, 0x87, 0xc0, 0x36, 0xb8, 0x77, 0xc4, 0xc5, 0xcb, 0xec, 0xdf, 0xee, 0xca, 0x99,
	0x2c, 0x86, 0xc3, 0xa2, 0xf1, 0xd7, 0x56, 0x68, 0xb6, 0x87, 0x68, 0x16, 0x65, 0xfe, 0xe3, 0xd8,
	0x0a, 0xf3, 0x73, 0xac, 0xb3, 0xb3, 0x92, 0xf9, 0xa0, 0x1a, 0x1c, 0x64, 0xce, 0xc7, 0x46, 0xa8,
	0x63, 0xcf, 0x2f, 0xd8, 0x1d, 0xdd, 0x0f, 0xa9, 0xc7, 0xc7, 0xbc, 0x55, 0xb9, 0xd4, 0x6d, 0x1d,
	0x39, 0xf0, 0xf1, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x39, 0x92, 0x5c, 0xac, 0x65, 0x02, 0x00,
	0x00,
}
