// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages/filters.proto

/*
Package filters is a generated protocol buffer package.

It is generated from these files:
	messages/filters.proto

It has these top-level messages:
	BoxFilter
	DeviceFilter
	UpdateFilter
*/
package filters

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import basetypes "github.com/roderm/audio-panel-protobuf/go/msg/basetypes"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BoxFilter struct {
	BoxIDs []string `protobuf:"bytes,2,rep,name=BoxIDs" json:"BoxIDs"`
}

func (m *BoxFilter) Reset()                    { *m = BoxFilter{} }
func (m *BoxFilter) String() string            { return proto.CompactTextString(m) }
func (*BoxFilter) ProtoMessage()               {}
func (*BoxFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BoxFilter) GetBoxIDs() []string {
	if m != nil {
		return m.BoxIDs
	}
	return nil
}

type DeviceFilter struct {
	BoxIDs    []string `protobuf:"bytes,2,rep,name=BoxIDs" json:"BoxIDs"`
	DeviceIDs []string `protobuf:"bytes,3,rep,name=DeviceIDs" json:"DeviceIDs"`
}

func (m *DeviceFilter) Reset()                    { *m = DeviceFilter{} }
func (m *DeviceFilter) String() string            { return proto.CompactTextString(m) }
func (*DeviceFilter) ProtoMessage()               {}
func (*DeviceFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DeviceFilter) GetBoxIDs() []string {
	if m != nil {
		return m.BoxIDs
	}
	return nil
}

func (m *DeviceFilter) GetDeviceIDs() []string {
	if m != nil {
		return m.DeviceIDs
	}
	return nil
}

type UpdateFilter struct {
	Types     []basetypes.UpdateType `protobuf:"varint,1,rep,packed,name=Types,enum=UpdateType" json:"Types"`
	BoxIDs    []string               `protobuf:"bytes,2,rep,name=BoxIDs" json:"BoxIDs"`
	DeviceIDs []string               `protobuf:"bytes,3,rep,name=DeviceIDs" json:"DeviceIDs"`
}

func (m *UpdateFilter) Reset()                    { *m = UpdateFilter{} }
func (m *UpdateFilter) String() string            { return proto.CompactTextString(m) }
func (*UpdateFilter) ProtoMessage()               {}
func (*UpdateFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UpdateFilter) GetTypes() []basetypes.UpdateType {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *UpdateFilter) GetBoxIDs() []string {
	if m != nil {
		return m.BoxIDs
	}
	return nil
}

func (m *UpdateFilter) GetDeviceIDs() []string {
	if m != nil {
		return m.DeviceIDs
	}
	return nil
}

func init() {
	proto.RegisterType((*BoxFilter)(nil), "BoxFilter")
	proto.RegisterType((*DeviceFilter)(nil), "DeviceFilter")
	proto.RegisterType((*UpdateFilter)(nil), "UpdateFilter")
}

func init() { proto.RegisterFile("messages/filters.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0xcb, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x4f, 0xcb, 0xcc, 0x29, 0x49, 0x2d, 0x2a, 0xd6, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x97, 0x92, 0x80, 0x8b, 0x27, 0x25, 0x16, 0xa7, 0x96, 0x54, 0x16, 0xa4, 0x42, 0x65,
	0x94, 0x94, 0xb9, 0x38, 0x9d, 0xf2, 0x2b, 0xdc, 0xc0, 0xaa, 0x85, 0xc4, 0xb8, 0xd8, 0x9c, 0xf2,
	0x2b, 0x3c, 0x5d, 0x8a, 0x25, 0x98, 0x14, 0x98, 0x35, 0x38, 0x83, 0xa0, 0x3c, 0x25, 0x17, 0x2e,
	0x1e, 0x97, 0xd4, 0xb2, 0xcc, 0xe4, 0x54, 0xfc, 0xea, 0x84, 0x64, 0xb8, 0x38, 0x21, 0xea, 0x40,
	0x52, 0xcc, 0x60, 0x29, 0x84, 0x80, 0x52, 0x3a, 0x17, 0x4f, 0x68, 0x41, 0x4a, 0x62, 0x09, 0xcc,
	0x14, 0x45, 0x2e, 0xd6, 0x10, 0x90, 0x4b, 0x24, 0x18, 0x15, 0x98, 0x35, 0xf8, 0x8c, 0xb8, 0xf5,
	0x20, 0xb2, 0x20, 0xb1, 0x20, 0x88, 0x0c, 0x79, 0x16, 0x39, 0x99, 0x47, 0x99, 0xa6, 0x67, 0x96,
	0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x17, 0xe5, 0xa7, 0xa4, 0x16, 0xe5, 0xea, 0x27,
	0x96, 0xa6, 0x64, 0xe6, 0xeb, 0x16, 0x24, 0xe6, 0xa5, 0xe6, 0xe8, 0x82, 0xbd, 0x9e, 0x54, 0x9a,
	0xa6, 0x9f, 0x9e, 0xaf, 0x9f, 0x5b, 0x9c, 0x0e, 0x0b, 0xac, 0x24, 0x36, 0xb0, 0x84, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0x0b, 0x51, 0x5e, 0xbd, 0x47, 0x01, 0x00, 0x00,
}
